### ISSUE TITLE
Use smaller Python Docker base image

### ISSUE THREAD

**Issue by peaceiris** [ponicode/dogstring-action#11]
https://github.com/ponicode/dogstring-action/blob/1e44b1cdffd2e8e51ba11552233e03fcb99ad8d1/Dockerfile#L1

Maybe, we can switch to python:3.7-slim-buster for fast execution.

**Comment by bbouffaut** [comment]
Hi @peaceiris , many thanks for this comment. This is very relevant. We will probably update our image based on your recommendation :+1:
